export enum ActionType {
  TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_USER = 'LOGOUT_USER',
  HANDLE_CHANGE = 'HANDLE_CHANGE',
  DISPLAY_ALERT = 'DISPLAY_ALERT',
  CLEAR_ALERT = 'CLEAR_ALERT',
  CLEAR_INPUTS = 'CLEAR_INPUTS',
}
